package com.csye6225.fall2018.yuchen.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Registrar")
public class Registrar {
    private String registrationId;
    private String offeringId;
    private String offeringType;
    private String perUnitPrice;

    public Registrar(){

    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "RegistrationId")
    public String getRegistrationId() {
        return registrationId;
    }

    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "OfferingId", attributeName = "OfferingId")
    public String getOfferingId() {
        return offeringId;
    }

    public void setOfferingId(String offeringId) {
        this.offeringId = offeringId;
    }

    @DynamoDBAttribute(attributeName = "OfferingType")
    public String getOfferingType() {
        return offeringType;
    }

    public void setOfferingType(String offeringType) {
        this.offeringType = offeringType;
    }

    @DynamoDBAttribute(attributeName = "PerUnitPrice")
    public String getPerUnitPrice() {
        return perUnitPrice;
    }

    public void setPerUnitPrice(String perUnitPrice) {
        this.perUnitPrice = perUnitPrice;
    }

    @DynamoDBIgnore
    @Override
    public String toString(){
        return "OfferingId=" + getOfferingId()+ ",OfferingType=" + getOfferingType()
                + ",PerUnitPrice=" + getPerUnitPrice();
    }
}
