package com.csye6225.fall2018.yuchen.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Announcement")
public class Announcement {
    private String id;
    private String announcementId;
    private String announcementText;
    private String boardId;

    public Announcement(){

    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return id;
    }

    public void setId(String professorId) {
        this.id = professorId;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "Announcement-Index", attributeName = "BoardId")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "Announcement-Index", attributeName = "AnnouncementId")
    public String getAnnouncementId() {
        return announcementId;
    }

    public void setAnnouncementId(String announcementId) {
        this.announcementId = announcementId;
    }

    @DynamoDBAttribute(attributeName = "AnnouncementText")
    public String getAnnouncementText() {
        return announcementText;
    }

    public void setAnnouncementText(String announcementText) {
        this.announcementText = announcementText;
    }

    @DynamoDBIgnore
    @Override
    public String toString(){
        return "BoardId=" + getBoardId()+ ",AnnouncementId=" + getAnnouncementId();
    }
}
