package com.csye6225.fall2018.yuchen.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Board")
public class Board {
    private String id;
    private String boardId;
    private String courseId;

    public Board(){

    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return id;
    }

    public void setId(String professorId) {
        this.id = professorId;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "BoardId", attributeName = "BoardId")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "CourseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    @DynamoDBIgnore
    @Override
    public String toString(){
        return "BoardId=" + getBoardId()+ ",CourseId=" + getCourseId();
    }
}
