package com.csye6225.fall2018.yuchen.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName = "Student")
public class Student {
    private String id;
    private String studentId;
    private String firstName;
    private String lastName;
    private String joiningDate;
    private String department;
    private List<String> registeredCourses;

    public Student(){

    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return id;
    }

    public void setId(String professorId) {
        this.id = professorId;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "StudentId", attributeName = "StudentId")
    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    @DynamoDBAttribute(attributeName = "FirstName")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "LastName")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "Department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "JoiningDate")
    public String getJoiningDate() {
        return joiningDate;
    }

    public void setJoiningDate(String joiningDate){
        this.joiningDate = joiningDate;
    }

    @DynamoDBAttribute(attributeName = "RegisteredCourses")
    public List<String> getRegisteredCourses() {
        return registeredCourses;
    }

    public void setRegisteredCourses(List<String> registeredCourses) {
        this.registeredCourses = registeredCourses;
    }

    @DynamoDBIgnore
    @Override
    public String toString(){
        return "StudentId=" + getStudentId()+ ",FirstName=" + getFirstName()+",Department="+getDepartment()+
                ",JoiningDate="+getJoiningDate();
    }
}
